// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrainTicketPlatformAPI.Data;

#nullable disable

namespace TrainTicketPlatformAPI.Migrations
{
    [DbContext(typeof(TrainTicketDbContext))]
    partial class TrainTicketDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TrainTicketPlatformAPI.Models.AdminAuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("AdminEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int?>("AdminUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("HttpMethod")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("StatusCode")
                        .HasColumnType("int");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(700)
                        .HasColumnType("nvarchar(700)");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("AdminUserId");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("EntityType");

                    b.ToTable("AdminAuditLogs");
                });

            modelBuilder.Entity("TrainTicketPlatformAPI.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BaseAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("BookingOrderId")
                        .HasColumnType("int");

                    b.Property<string>("BookingReference")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasDefaultValueSql("'BKG-' + CONVERT(varchar(36), NEWID())");

                    b.Property<string>("BookingStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasDefaultValue("PendingPayment");

                    b.Property<DateTime?>("CancellationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime?>("ConfirmedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasDefaultValue("PLN");

                    b.Property<string>("DiscountCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasDefaultValue("normal");

                    b.Property<string>("DiscountName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasDefaultValue("Normal Ticket");

                    b.Property<decimal>("DiscountPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("DogTicketCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ExtraChargeAmount")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("GuestEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("bit");

                    b.Property<string>("JourneyDirection")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasDefaultValue("Outbound");

                    b.Property<int>("JourneySegmentIndex")
                        .HasColumnType("int");

                    b.Property<int>("LargeBaggageTicketCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<decimal>("LoyaltyDiscountAmount")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<int>("LoyaltyPointsRedeemed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("PassengerName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PassengerType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasDefaultValue("Adult");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasDefaultValue("Pending");

                    b.Property<DateTime?>("RefundedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("SeatId")
                        .HasColumnType("int");

                    b.Property<int?>("SegmentArrivalOrder")
                        .HasColumnType("int");

                    b.Property<int?>("SegmentArrivalStationId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SegmentArrivalTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SegmentDepartureOrder")
                        .HasColumnType("int");

                    b.Property<int?>("SegmentDepartureStationId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SegmentDepartureTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("TicketEmailRecipient")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasDefaultValue("");

                    b.Property<DateTime?>("TicketEmailSentAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TicketEmailStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasDefaultValue("");

                    b.Property<DateTime?>("TicketIssuedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TicketNumber")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasDefaultValue("");

                    b.Property<string>("TicketQrPayload")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1200)
                        .HasColumnType("nvarchar(1200)")
                        .HasDefaultValue("");

                    b.Property<int>("TrainId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TravelDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TripId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookingOrderId");

                    b.HasIndex("BookingReference")
                        .IsUnique();

                    b.HasIndex("GuestEmail");

                    b.HasIndex("SegmentArrivalStationId");

                    b.HasIndex("SegmentDepartureStationId");

                    b.HasIndex("TicketNumber")
                        .IsUnique()
                        .HasFilter("[TicketNumber] <> ''");

                    b.HasIndex("UserId");

                    b.HasIndex("SeatId", "TravelDate");

                    b.HasIndex("TripId", "SeatId")
                        .HasFilter("[IsCancelled] = 0 AND [TripId] IS NOT NULL AND [BookingStatus] IN ('PendingPayment', 'Confirmed')");

                    b.HasIndex("TripId", "TravelDate");

                    b.HasIndex("BookingOrderId", "JourneyDirection", "JourneySegmentIndex");

                    b.HasIndex("TrainId", "SeatId", "TravelDate")
                        .IsUnique()
                        .HasFilter("[IsCancelled] = 0 AND [TripId] IS NULL AND [BookingStatus] IN ('PendingPayment', 'Confirmed')");

                    b.HasIndex("TripId", "SeatId", "SegmentDepartureOrder", "SegmentArrivalOrder");

                    b.ToTable("Bookings", t =>
                        {
                            t.HasCheckConstraint("CK_Bookings_BookingStatus", "[BookingStatus] IN ('PendingPayment', 'Confirmed', 'Cancelled', 'Expired', 'Refunded')");

                            t.HasCheckConstraint("CK_Bookings_PaymentStatus", "[PaymentStatus] IN ('Pending', 'Successful', 'Failed', 'Refunded')");
                        });
                });

            modelBuilder.Entity("TrainTicketPlatformAPI.Models.BookingOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BookingStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasDefaultValue("PendingPayment");

                    b.Property<DateTime?>("ConfirmedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("GuestEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsItinerary")
                        .HasColumnType("bit");

                    b.Property<string>("ItineraryId")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int?>("JourneyArrivalStationId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("JourneyArrivalTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("JourneyDepartureStationId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("JourneyDepartureTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("LoyaltyDiscountAmount")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<int>("LoyaltyPointsRedeemed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("OrderReference")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasDefaultValue("Pending");

                    b.Property<int>("SegmentCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("TripType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasDefaultValue("OneWay");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GuestEmail");

                    b.HasIndex("ItineraryId");

                    b.HasIndex("OrderReference")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("BookingOrders", t =>
                        {
                            t.HasCheckConstraint("CK_BookingOrders_BookingStatus", "[BookingStatus] IN ('PendingPayment', 'Confirmed', 'Cancelled', 'Expired', 'Refunded')");

                            t.HasCheckConstraint("CK_BookingOrders_PaymentStatus", "[PaymentStatus] IN ('Pending', 'Successful', 'Failed', 'Refunded')");
                        });
                });

            modelBuilder.Entity("TrainTicketPlatformAPI.Models.BookingReport", b =>
                {
                    b.Property<DateTime>("From")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("To")
                        .HasColumnType("datetime2");

                    b.Property<int>("TotalBookings")
                        .HasColumnType("int");

                    b.Property<int>("TotalCancellations")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalRevenue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.ToTable("bookingReports");
                });

            modelBuilder.Entity("TrainTicketPlatformAPI.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("TrainTicketPlatformAPI.Models.DiscountRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DocumentHint")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("EligibleClass")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<decimal>("Percent")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasDefaultValue("Active");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("DiscountRules");
                });

            modelBuilder.Entity("TrainTicketPlatformAPI.Models.Fare", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClassType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TripId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TripId");

                    b.ToTable("Fares");
                });

            modelBuilder.Entity("TrainTicketPlatformAPI.Models.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BillingAddress")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasDefaultValue("");

                    b.Property<int?>("BookingId")
                        .HasColumnType("int");

                    b.Property<int?>("BookingOrderId")
                        .HasColumnType("int");

                    b.Property<string>("BuyerEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("BuyerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("BuyerTaxId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasDefaultValue("");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasDefaultValue("PLN");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime>("IssuedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("NetAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasDefaultValue("Issued");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<decimal>("VatAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BookingId")
                        .IsUnique()
                        .HasFilter("[BookingId] IS NOT NULL");

                    b.HasIndex("BookingOrderId")
                        .IsUnique()
                        .HasFilter("[BookingOrderId] IS NOT NULL");

                    b.HasIndex("InvoiceNumber")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Invoices", t =>
                        {
                            t.HasCheckConstraint("CK_Invoices_Status", "[Status] IN ('Issued', 'Cancelled')");

                            t.HasCheckConstraint("CK_Invoices_Target", "([BookingId] IS NOT NULL AND [BookingOrderId] IS NULL) OR ([BookingId] IS NULL AND [BookingOrderId] IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("TrainTicketPlatformAPI.Models.Locality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("StateRegionId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("StateRegionId", "Name", "Type");

                    b.ToTable("Localities");
                });

            modelBuilder.Entity("TrainTicketPlatformAPI.Models.LoyaltyAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExpiringPoints")
                        .HasColumnType("int");

                    b.Property<int>("PendingPoints")
                        .HasColumnType("int");

                    b.Property<int>("RedeemablePoints")
                        .HasColumnType("int");

                    b.Property<decimal>("RedeemableValuePln")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("LoyaltyAccounts");
                });

            modelBuilder.Entity("TrainTicketPlatformAPI.Models.LoyaltyTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BookingId")
                        .HasColumnType("int");

                    b.Property<int?>("BookingOrderId")
                        .HasColumnType("int");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasDefaultValue("PLN");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("nvarchar(240)");

                    b.Property<DateTime?>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("LoyaltyAccountId")
                        .HasColumnType("int");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<decimal>("SourceAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime>("TransactionDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime>("ValidFromUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("BookingOrderId");

                    b.HasIndex("LoyaltyAccountId");

                    b.ToTable("LoyaltyTransactions", t =>
                        {
                            t.HasCheckConstraint("CK_LoyaltyTransactions_Status", "[Status] IN ('Pending', 'Available', 'Redeemed', 'Expired', 'Cancelled')");

                            t.HasCheckConstraint("CK_LoyaltyTransactions_Type", "[Type] IN ('TicketPurchase', 'Redemption', 'Adjustment')");
                        });
                });

            modelBuilder.Entity("TrainTicketPlatformAPI.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("BookingId")
                        .HasColumnType("int");

                    b.Property<int?>("BookingOrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("LoyaltyDiscountAmount")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<int>("LoyaltyPointsRedeemed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentIntentId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("PaymentMethodToken")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("BookingOrderId");

                    b.HasIndex("PaymentIntentId")
                        .IsUnique();

                    b.ToTable("Payments", t =>
                        {
                            t.HasCheckConstraint("CK_Payments_Status", "[Status] IN ('Successful', 'Failed', 'Refunded')");

                            t.HasCheckConstraint("CK_Payments_Target", "([BookingId] IS NOT NULL AND [BookingOrderId] IS NULL) OR ([BookingId] IS NULL AND [BookingOrderId] IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("TrainTicketPlatformAPI.Models.RollingStockOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int?>("FleetCount")
                        .HasColumnType("int");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("MaxSpeed")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Series")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasDefaultValue("Active");

                    b.Property<int?>("UnitCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Category", "Series")
                        .IsUnique();

                    b.ToTable("RollingStockOptions");
                });

            modelBuilder.Entity("TrainTicketPlatformAPI.Models.Seat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClassType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Coach")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("TrainId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TrainId", "Coach", "Number")
                        .IsUnique();

                    b.ToTable("Seats");
                });

            modelBuilder.Entity("TrainTicketPlatformAPI.Models.StateRegion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId", "Code")
                        .IsUnique();

                    b.ToTable("StateRegions");
                });

            modelBuilder.Entity("TrainTicketPlatformAPI.Models.Station", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int?>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("ExternalSource")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasDefaultValue("");

                    b.Property<int?>("ExternalStationId")
                        .HasColumnType("int");

                    b.Property<int?>("LocalityId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedCode")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasComputedColumnSql("UPPER(LTRIM(RTRIM([Code])))", true);

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasComputedColumnSql("UPPER(LTRIM(RTRIM([Name])))", true);

                    b.Property<int?>("StateRegionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CountryId");

                    b.HasIndex("LocalityId");

                    b.HasIndex("NormalizedCode")
                        .IsUnique();

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.HasIndex("StateRegionId");

                    b.HasIndex("ExternalSource", "ExternalStationId")
                        .IsUnique()
                        .HasFilter("[ExternalSource] <> '' AND [ExternalStationId] IS NOT NULL");

                    b.ToTable("Stations", t =>
                        {
                            t.HasCheckConstraint("CK_Stations_Code_NotBlank", "LEN(LTRIM(RTRIM([Code]))) > 0");

                            t.HasCheckConstraint("CK_Stations_Name_NotBlank", "LEN(LTRIM(RTRIM([Name]))) > 0");
                        });
                });

            modelBuilder.Entity("TrainTicketPlatformAPI.Models.TicketEmailDelivery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ProviderMessageId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("RecipientEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("RequestedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SentAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.ToTable("TicketEmailDeliveries");
                });

            modelBuilder.Entity("TrainTicketPlatformAPI.Models.Train", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ArrivalStation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ArrivalTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("CarriageCount")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasDefaultValue("");

                    b.Property<string>("DepartureStation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExternalCarrierCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasDefaultValue("");

                    b.Property<string>("ExternalCommercialCategorySymbol")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasDefaultValue("");

                    b.Property<string>("ExternalInternationalArrivalNumber")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasDefaultValue("");

                    b.Property<string>("ExternalInternationalDepartureNumber")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasDefaultValue("");

                    b.Property<string>("ExternalNationalNumber")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasDefaultValue("");

                    b.Property<string>("ExternalSource")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasDefaultValue("");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SeatsPerCarriage")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasDefaultValue("Active");

                    b.Property<string>("Type")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasDefaultValue("InterCity");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasFilter("[Code] <> ''");

                    b.HasIndex("ExternalSource", "ExternalCarrierCode", "ExternalCommercialCategorySymbol", "ExternalNationalNumber");

                    b.ToTable("Trains");
                });

            modelBuilder.Entity("TrainTicketPlatformAPI.Models.TrainCarriage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClassType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Coach")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("HasAccessibleSpace")
                        .HasColumnType("bit");

                    b.Property<bool>("HasBikeSpace")
                        .HasColumnType("bit");

                    b.Property<bool>("HasDiningSection")
                        .HasColumnType("bit");

                    b.Property<bool>("HasFamilyCompartment")
                        .HasColumnType("bit");

                    b.Property<string>("LayoutType")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<int>("SeatCount")
                        .HasColumnType("int");

                    b.Property<int>("TrainId")
                        .HasColumnType("int");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("TrainId", "Coach")
                        .IsUnique();

                    b.ToTable("TrainCarriages");
                });

            modelBuilder.Entity("TrainTicketPlatformAPI.Models.TrainRoute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminDisplayName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasDefaultValue("");

                    b.Property<int>("ArrivalStationId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasDefaultValue("");

                    b.Property<int>("DepartureStationId")
                        .HasColumnType("int");

                    b.Property<decimal>("DistanceKm")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("EstimatedDurationMinutes")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("ExternalOperatingDate")
                        .HasColumnType("date");

                    b.Property<int?>("ExternalOrderId")
                        .HasColumnType("int");

                    b.Property<int?>("ExternalScheduleId")
                        .HasColumnType("int");

                    b.Property<string>("ExternalSource")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasDefaultValue("");

                    b.Property<int?>("ExternalTrainOrderId")
                        .HasColumnType("int");

                    b.Property<string>("IntermediateStops")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasDefaultValue("");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(240)
                        .HasColumnType("nvarchar(240)")
                        .HasDefaultValue("");

                    b.Property<string>("OperatingDays")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasDefaultValue("Daily");

                    b.Property<string>("RouteFingerprint")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1200)
                        .HasColumnType("nvarchar(1200)")
                        .HasDefaultValue("");

                    b.HasKey("Id");

                    b.HasIndex("ArrivalStationId");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasFilter("[Code] <> ''");

                    b.HasIndex("DepartureStationId");

                    b.HasIndex("ExternalSource", "ExternalScheduleId", "ExternalOrderId", "ExternalOperatingDate")
                        .IsUnique()
                        .HasFilter("[ExternalSource] <> '' AND [ExternalScheduleId] IS NOT NULL AND [ExternalOrderId] IS NOT NULL AND [ExternalOperatingDate] IS NOT NULL");

                    b.ToTable("TrainRoutes");
                });

            modelBuilder.Entity("TrainTicketPlatformAPI.Models.TrainRouteStop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ArrivalDayOffset")
                        .HasColumnType("int");

                    b.Property<int?>("ArrivalOffsetMinutes")
                        .HasColumnType("int");

                    b.Property<int?>("DepartureDayOffset")
                        .HasColumnType("int");

                    b.Property<int?>("DepartureOffsetMinutes")
                        .HasColumnType("int");

                    b.Property<string>("ExternalArrivalTrainNumber")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasDefaultValue("");

                    b.Property<string>("ExternalDepartureTrainNumber")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasDefaultValue("");

                    b.Property<int?>("ExternalStationId")
                        .HasColumnType("int");

                    b.Property<int?>("ExternalStopTypeId")
                        .HasColumnType("int");

                    b.Property<string>("ExternalStopTypeName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasDefaultValue("");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("StationId")
                        .HasColumnType("int");

                    b.Property<int>("StopOrder")
                        .HasColumnType("int");

                    b.Property<string>("StopType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Track")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TrainRouteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StationId");

                    b.HasIndex("ExternalStationId", "TrainRouteId");

                    b.HasIndex("TrainRouteId", "StationId")
                        .IsUnique();

                    b.HasIndex("TrainRouteId", "StopOrder")
                        .IsUnique();

                    b.ToTable("TrainRouteStops");
                });

            modelBuilder.Entity("TrainTicketPlatformAPI.Models.Trip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ArrivalTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CancellationReason")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasDefaultValue("");

                    b.Property<int>("DelayMinutes")
                        .HasColumnType("int");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisruptionMessage")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasDefaultValue("");

                    b.Property<string>("DisruptionSeverity")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("");

                    b.Property<DateTime?>("ExternalImportedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly?>("ExternalOperatingDate")
                        .HasColumnType("date");

                    b.Property<int?>("ExternalOrderId")
                        .HasColumnType("int");

                    b.Property<string>("ExternalRawVersion")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasDefaultValue("");

                    b.Property<int?>("ExternalScheduleId")
                        .HasColumnType("int");

                    b.Property<string>("ExternalSource")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasDefaultValue("");

                    b.Property<int?>("ExternalTrainOrderId")
                        .HasColumnType("int");

                    b.Property<string>("OriginalPlatform")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasDefaultValue("");

                    b.Property<string>("OriginalTrack")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasDefaultValue("");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasDefaultValue("");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Track")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasDefaultValue("");

                    b.Property<int>("TrainId")
                        .HasColumnType("int");

                    b.Property<int>("TrainRouteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TrainId");

                    b.HasIndex("ExternalSource", "ExternalTrainOrderId");

                    b.HasIndex("TrainRouteId", "DepartureTime");

                    b.HasIndex("ExternalSource", "ExternalScheduleId", "ExternalOrderId", "ExternalOperatingDate")
                        .IsUnique()
                        .HasFilter("[ExternalSource] <> '' AND [ExternalScheduleId] IS NOT NULL AND [ExternalOrderId] IS NOT NULL AND [ExternalOperatingDate] IS NOT NULL");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("TrainTicketPlatformAPI.Models.TripCarriageSegment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DestinationLabel")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)")
                        .HasDefaultValue("");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<int?>("FromRouteStopId")
                        .HasColumnType("int");

                    b.Property<bool>("IsBookable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Notes")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasDefaultValue("");

                    b.Property<string>("PortionCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasDefaultValue("");

                    b.Property<int?>("ToRouteStopId")
                        .HasColumnType("int");

                    b.Property<int>("TrainCarriageId")
                        .HasColumnType("int");

                    b.Property<int>("TripId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FromRouteStopId");

                    b.HasIndex("ToRouteStopId");

                    b.HasIndex("TrainCarriageId");

                    b.HasIndex("TripId", "DisplayOrder");

                    b.HasIndex("TripId", "PortionCode");

                    b.HasIndex("TripId", "TrainCarriageId");

                    b.HasIndex("TripId", "FromRouteStopId", "ToRouteStopId");

                    b.ToTable("TripCarriageSegments");
                });

            modelBuilder.Entity("TrainTicketPlatformAPI.Models.TripServiceIdentity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CarrierCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasDefaultValue("");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasDefaultValue("");

                    b.Property<string>("DisplayNumber")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasDefaultValue("");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("ExternalSource")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasDefaultValue("");

                    b.Property<int?>("FromRouteStopId")
                        .HasColumnType("int");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<string>("Number")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasDefaultValue("");

                    b.Property<string>("ServiceCategory")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)")
                        .HasDefaultValue("");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)")
                        .HasDefaultValue("");

                    b.Property<int?>("ToRouteStopId")
                        .HasColumnType("int");

                    b.Property<int>("TripId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FromRouteStopId");

                    b.HasIndex("ToRouteStopId");

                    b.HasIndex("TripId", "DisplayOrder");

                    b.HasIndex("TripId", "IsPrimary");

                    b.HasIndex("ExternalSource", "CarrierCode", "ServiceCategory", "Number");

                    b.ToTable("TripServiceIdentities");
                });

            modelBuilder.Entity("TrainTicketPlatformAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasDefaultValue("");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasComputedColumnSql("UPPER(LTRIM(RTRIM([Email])))", true);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasDefaultValue("Active");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TrainTicketPlatformAPI.Models.Booking", b =>
                {
                    b.HasOne("TrainTicketPlatformAPI.Models.BookingOrder", "BookingOrder")
                        .WithMany("Bookings")
                        .HasForeignKey("BookingOrderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TrainTicketPlatformAPI.Models.Seat", "Seat")
                        .WithMany("Bookings")
                        .HasForeignKey("SeatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TrainTicketPlatformAPI.Models.Station", "SegmentArrivalStation")
                        .WithMany()
                        .HasForeignKey("SegmentArrivalStationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TrainTicketPlatformAPI.Models.Station", "SegmentDepartureStation")
                        .WithMany()
                        .HasForeignKey("SegmentDepartureStationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TrainTicketPlatformAPI.Models.Train", "Train")
                        .WithMany("Bookings")
                        .HasForeignKey("TrainId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TrainTicketPlatformAPI.Models.Trip", "Trip")
                        .WithMany("Bookings")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TrainTicketPlatformAPI.Models.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BookingOrder");

                    b.Navigation("Seat");

                    b.Navigation("SegmentArrivalStation");

                    b.Navigation("SegmentDepartureStation");

                    b.Navigation("Train");

                    b.Navigation("Trip");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TrainTicketPlatformAPI.Models.BookingOrder", b =>
                {
                    b.HasOne("TrainTicketPlatformAPI.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("User");
                });

            modelBuilder.Entity("TrainTicketPlatformAPI.Models.Fare", b =>
                {
                    b.HasOne("TrainTicketPlatformAPI.Models.Trip", "Trip")
                        .WithMany("Fares")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("TrainTicketPlatformAPI.Models.Invoice", b =>
                {
                    b.HasOne("TrainTicketPlatformAPI.Models.Booking", "Booking")
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TrainTicketPlatformAPI.Models.BookingOrder", "BookingOrder")
                        .WithMany()
                        .HasForeignKey("BookingOrderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TrainTicketPlatformAPI.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Booking");

                    b.Navigation("BookingOrder");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TrainTicketPlatformAPI.Models.Locality", b =>
                {
                    b.HasOne("TrainTicketPlatformAPI.Models.StateRegion", "StateRegion")
                        .WithMany("Localities")
                        .HasForeignKey("StateRegionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("StateRegion");
                });

            modelBuilder.Entity("TrainTicketPlatformAPI.Models.LoyaltyAccount", b =>
                {
                    b.HasOne("TrainTicketPlatformAPI.Models.User", "User")
                        .WithOne()
                        .HasForeignKey("TrainTicketPlatformAPI.Models.LoyaltyAccount", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TrainTicketPlatformAPI.Models.LoyaltyTransaction", b =>
                {
                    b.HasOne("TrainTicketPlatformAPI.Models.Booking", "Booking")
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TrainTicketPlatformAPI.Models.BookingOrder", "BookingOrder")
                        .WithMany()
                        .HasForeignKey("BookingOrderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TrainTicketPlatformAPI.Models.LoyaltyAccount", "LoyaltyAccount")
                        .WithMany("Transactions")
                        .HasForeignKey("LoyaltyAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("BookingOrder");

                    b.Navigation("LoyaltyAccount");
                });

            modelBuilder.Entity("TrainTicketPlatformAPI.Models.Payment", b =>
                {
                    b.HasOne("TrainTicketPlatformAPI.Models.Booking", "Booking")
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TrainTicketPlatformAPI.Models.BookingOrder", "BookingOrder")
                        .WithMany()
                        .HasForeignKey("BookingOrderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Booking");

                    b.Navigation("BookingOrder");
                });

            modelBuilder.Entity("TrainTicketPlatformAPI.Models.Seat", b =>
                {
                    b.HasOne("TrainTicketPlatformAPI.Models.Train", "Train")
                        .WithMany()
                        .HasForeignKey("TrainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Train");
                });

            modelBuilder.Entity("TrainTicketPlatformAPI.Models.StateRegion", b =>
                {
                    b.HasOne("TrainTicketPlatformAPI.Models.Country", "Country")
                        .WithMany("StateRegions")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("TrainTicketPlatformAPI.Models.Station", b =>
                {
                    b.HasOne("TrainTicketPlatformAPI.Models.Country", "Country")
                        .WithMany("Stations")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TrainTicketPlatformAPI.Models.Locality", "Locality")
                        .WithMany("Stations")
                        .HasForeignKey("LocalityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TrainTicketPlatformAPI.Models.StateRegion", "StateRegion")
                        .WithMany("Stations")
                        .HasForeignKey("StateRegionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Country");

                    b.Navigation("Locality");

                    b.Navigation("StateRegion");
                });

            modelBuilder.Entity("TrainTicketPlatformAPI.Models.TicketEmailDelivery", b =>
                {
                    b.HasOne("TrainTicketPlatformAPI.Models.Booking", "Booking")
                        .WithMany("TicketEmailDeliveries")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("TrainTicketPlatformAPI.Models.TrainCarriage", b =>
                {
                    b.HasOne("TrainTicketPlatformAPI.Models.Train", "Train")
                        .WithMany("Carriages")
                        .HasForeignKey("TrainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Train");
                });

            modelBuilder.Entity("TrainTicketPlatformAPI.Models.TrainRoute", b =>
                {
                    b.HasOne("TrainTicketPlatformAPI.Models.Station", "ArrivalStation")
                        .WithMany("ArrivalRoutes")
                        .HasForeignKey("ArrivalStationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TrainTicketPlatformAPI.Models.Station", "DepartureStation")
                        .WithMany("DepartureRoutes")
                        .HasForeignKey("DepartureStationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ArrivalStation");

                    b.Navigation("DepartureStation");
                });

            modelBuilder.Entity("TrainTicketPlatformAPI.Models.TrainRouteStop", b =>
                {
                    b.HasOne("TrainTicketPlatformAPI.Models.Station", "Station")
                        .WithMany()
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TrainTicketPlatformAPI.Models.TrainRoute", "TrainRoute")
                        .WithMany("RouteStops")
                        .HasForeignKey("TrainRouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Station");

                    b.Navigation("TrainRoute");
                });

            modelBuilder.Entity("TrainTicketPlatformAPI.Models.Trip", b =>
                {
                    b.HasOne("TrainTicketPlatformAPI.Models.Train", "Train")
                        .WithMany("Trips")
                        .HasForeignKey("TrainId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TrainTicketPlatformAPI.Models.TrainRoute", "TrainRoute")
                        .WithMany("Trips")
                        .HasForeignKey("TrainRouteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Train");

                    b.Navigation("TrainRoute");
                });

            modelBuilder.Entity("TrainTicketPlatformAPI.Models.TripCarriageSegment", b =>
                {
                    b.HasOne("TrainTicketPlatformAPI.Models.TrainRouteStop", "FromRouteStop")
                        .WithMany()
                        .HasForeignKey("FromRouteStopId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TrainTicketPlatformAPI.Models.TrainRouteStop", "ToRouteStop")
                        .WithMany()
                        .HasForeignKey("ToRouteStopId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TrainTicketPlatformAPI.Models.TrainCarriage", "TrainCarriage")
                        .WithMany("TripSegments")
                        .HasForeignKey("TrainCarriageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TrainTicketPlatformAPI.Models.Trip", "Trip")
                        .WithMany("CarriageSegments")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FromRouteStop");

                    b.Navigation("ToRouteStop");

                    b.Navigation("TrainCarriage");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("TrainTicketPlatformAPI.Models.TripServiceIdentity", b =>
                {
                    b.HasOne("TrainTicketPlatformAPI.Models.TrainRouteStop", "FromRouteStop")
                        .WithMany()
                        .HasForeignKey("FromRouteStopId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TrainTicketPlatformAPI.Models.TrainRouteStop", "ToRouteStop")
                        .WithMany()
                        .HasForeignKey("ToRouteStopId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TrainTicketPlatformAPI.Models.Trip", "Trip")
                        .WithMany("ServiceIdentities")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FromRouteStop");

                    b.Navigation("ToRouteStop");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("TrainTicketPlatformAPI.Models.Booking", b =>
                {
                    b.Navigation("TicketEmailDeliveries");
                });

            modelBuilder.Entity("TrainTicketPlatformAPI.Models.BookingOrder", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("TrainTicketPlatformAPI.Models.Country", b =>
                {
                    b.Navigation("StateRegions");

                    b.Navigation("Stations");
                });

            modelBuilder.Entity("TrainTicketPlatformAPI.Models.Locality", b =>
                {
                    b.Navigation("Stations");
                });

            modelBuilder.Entity("TrainTicketPlatformAPI.Models.LoyaltyAccount", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("TrainTicketPlatformAPI.Models.Seat", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("TrainTicketPlatformAPI.Models.StateRegion", b =>
                {
                    b.Navigation("Localities");

                    b.Navigation("Stations");
                });

            modelBuilder.Entity("TrainTicketPlatformAPI.Models.Station", b =>
                {
                    b.Navigation("ArrivalRoutes");

                    b.Navigation("DepartureRoutes");
                });

            modelBuilder.Entity("TrainTicketPlatformAPI.Models.Train", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Carriages");

                    b.Navigation("Trips");
                });

            modelBuilder.Entity("TrainTicketPlatformAPI.Models.TrainCarriage", b =>
                {
                    b.Navigation("TripSegments");
                });

            modelBuilder.Entity("TrainTicketPlatformAPI.Models.TrainRoute", b =>
                {
                    b.Navigation("RouteStops");

                    b.Navigation("Trips");
                });

            modelBuilder.Entity("TrainTicketPlatformAPI.Models.Trip", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("CarriageSegments");

                    b.Navigation("Fares");

                    b.Navigation("ServiceIdentities");
                });

            modelBuilder.Entity("TrainTicketPlatformAPI.Models.User", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
